Traceback (most recent call last):
  File "C:\Users\jonas\PycharmProjects\ducks-riding-lamas\main.py", line 116, in <module>
    model_path = dqn_agent.train(
                 ^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\PycharmProjects\ducks-riding-lamas\agent_dqn\dqn_agent.py", line 193, in train
    q_mean, q_max, loss = self.train_iterate(states, actions, rewards, next_states, dones, indices, weights)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jonas\PycharmProjects\ducks-riding-lamas\venv\Lib\site-packages\tensorflow\python\util\traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\jonas\AppData\Local\Temp\__autograph_generated_filenyki2lqg.py", line 39, in tf__train_iterate
    ag__.if_stmt(ag__.ld(self).log_to_wandb, if_body, else_body, get_state, set_state, (), 0)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: in user code:

    File "C:\Users\jonas\PycharmProjects\ducks-riding-lamas\agent_dqn\dqn_agent.py", line 134, in train_iterate  *
        if self.log_to_wandb:

    AttributeError: 'DQNAgent' object has no attribute 'log_to_wandb'
